export const MOVIES = [
    {
        title: "The Shawshank Redemption",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        genres: ["Drama"],
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
        releaseDate: new Date("1994-09-23"),
        duration: 142,
        rating: 9.3,
        posterPath: "https://example.com/posters/shawshank.jpg",
    },
    {
        title: "Inception",
        description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a CEO's mind.",
        genres: ["Action", "Sci-Fi", "Thriller"],
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
        releaseDate: new Date("2010-07-16"),
        duration: 148,
        rating: 8.8,
        posterPath: "https://example.com/posters/inception.jpg",
    },
    {
        title: "The Dark Knight",
        description: "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on Gotham City.",
        genres: ["Action", "Crime", "Drama"],
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        releaseDate: new Date("2008-07-18"),
        duration: 152,
        rating: 9.0,
        posterPath: "https://example.com/posters/dark_knight.jpg",
    },
    {
        title: "Interstellar",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        genres: ["Adventure", "Drama", "Sci-Fi"],
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        releaseDate: new Date("2014-11-07"),
        duration: 169,
        rating: 8.6,
        posterPath: "https://example.com/posters/interstellar.jpg",
    },
    {
        title: "Forrest Gump",
        description: "The presidencies of Kennedy and Johnson, the Vietnam War, and more unfold through the perspective of an Alabama man with an IQ of 75.",
        genres: ["Drama", "Romance"],
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        releaseDate: new Date("1994-07-06"),
        duration: 142,
        rating: 8.8,
        posterPath: "https://example.com/posters/forrest_gump.jpg",
    },
    {
        title: "The Matrix",
        description: "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.",
        genres: ["Action", "Sci-Fi"],
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        releaseDate: new Date("1999-03-31"),
        duration: 136,
        rating: 8.7,
        posterPath: "https://example.com/posters/matrix.jpg",
    },
    {
        title: "Gladiator",
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
        genres: ["Action", "Adventure", "Drama"],
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
        releaseDate: new Date("2000-05-05"),
        duration: 155,
        rating: 8.5,
        posterPath: "https://example.com/posters/gladiator.jpg",
    },
    {
        title: "Pulp Fiction",
        description: "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in a tale of violence and redemption.",
        genres: ["Crime", "Drama"],
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        releaseDate: new Date("1994-10-14"),
        duration: 154,
        rating: 8.9,
        posterPath: "https://example.com/posters/pulp_fiction.jpg",
    },
    {
        title: "Avengers: Endgame",
        description: "After the devastating events of Infinity War, the Avengers assemble once more to undo Thanos's actions.",
        genres: ["Action", "Adventure", "Sci-Fi"],
        cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
        releaseDate: new Date("2019-04-26"),
        duration: 181,
        rating: 8.4,
        posterPath: "https://example.com/posters/endgame.jpg",
    },
    {
        title: "Parasite",
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        genres: ["Comedy", "Drama", "Thriller"],
        cast: ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Jo"],
        releaseDate: new Date("2019-11-08"),
        duration: 132,
        rating: 8.6,
        posterPath: "https://example.com/posters/parasite.jpg",
    }
];


